<?php
$NOMBRE_APP = "Sistema de Matrícula del Colegio de Palmares";
$URL_PAGINA_INGRESO = "./";
$URL_CARPETA_INTERFAZ = "./interfaz";
$MODO_ALTA = "A";
$MODO_CAMBIO = "C";
$MAX_NUM_RESULTADOS_X_PAGINA = 5;
$ID_ITEM_NULO = 0;
$ID_ITEM_NO_SELECCIONADO_EN_LISTA_SELECCION = $ID_ITEM_NULO;
$MAX_TIEMPO_TRANSCURRIDO_SEGUNDOS_DESDE_ULTIMO_ACCESO_SESION = 5*60; // Se fija el máximo tiempo transcurrido en 5 minutos
$FORMATO_FECHAS_SQL = "%Y-%m-%d";
$FORMATO_FECHAS_CONTROLES_FECHA = "yy-mm-dd";
$FORMATO_FECHAS_DESGLOSE = "%d/%m/%Y";
$FORMATO_FECHAS_HORAS_DESGLOSE = "%d/%m/%Y %h:%i:%s %p";
$TAMANO_MAXIMO_PALABRAS = 100;
$MOSTRAR_DATOS_DEPURACION = 1;
?>
